language: clojure
services: postgreSQL
env:
  - DATABASE_HOST="127.0.0.1:5432/wheelcrowd" DATABASE_USER="postgres"
before_script:
  - psql -c 'create database wheelcrowd;' -U postgres
  - lein ragtime migrate
